# Generated by Django 4.0.1 on 2022-01-26 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='repeatPassword',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intake',
            name='edate',
            field=models.DateField(verbose_name=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='intake',
            name='sdate',
            field=models.DateField(verbose_name=datetime.datetime.now),
        ),
    ]
