# Generated by Django 4.0.1 on 2022-01-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0003_alter_intake_edate_alter_intake_sdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myuser',
        ),
    ]
