# Generated by Django 4.0.1 on 2022-01-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0004_delete_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='promotion',
        ),
    ]
