# Generated by Django 4.0.1 on 2022-01-27 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0005_remove_trainee_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='fullname',
            field=models.CharField(default='intake42', max_length=20),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(default='os', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='intake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='affairs.intake'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='affairs.track'),
        ),
    ]
