# Generated by Django 4.0.1 on 2022-01-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0006_alter_intake_fullname_alter_track_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='intake',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='track',
            field=models.CharField(max_length=20),
        ),
    ]
