# Generated by Django 4.0.1 on 2022-01-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0007_alter_trainee_intake_alter_trainee_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='bdate',
            field=models.DateField(default=None),
        ),
    ]
