# Generated by Django 4.0.1 on 2022-02-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0008_alter_trainee_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='bdate',
            field=models.DateField(),
        ),
    ]
